FROM mongo:6.0

# Instala o curl
RUN apt-get update && apt-get install -y curl

# Copia o script para dentro da imagem
COPY mongo-init/docker-entrypoint.sh /usr/local/bin/

# Dá permissão de execução
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Usa esse script como ponto de entrada
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
